WINDOW_LENGTH = 900
WINDOW_WIDTH = 1000
SQUARE_SIZE = 125

NUMBER_OF_ROW = 7
NUMBER_OF_COL = 6

# the coordinates where the board should be paint in
X_START = (WINDOW_WIDTH - SQUARE_SIZE * NUMBER_OF_COL) // 2 - 100
Y_START = (WINDOW_LENGTH - SQUARE_SIZE * NUMBER_OF_ROW) // 2

# all the parameters needed for the Insert Arrow button
INSERT_ARROW_BUTTON_LENGTH = 70
INSERT_ARROW_BUTTON_WIDTH = 100
INSERT_ARROW_BUTTON_X = X_START + SQUARE_SIZE * (NUMBER_OF_COL + 0.5)
INSERT_ARROW_BUTTON_Y = Y_START + SQUARE_SIZE * (NUMBER_OF_ROW - 1)
